### ISSUE TITLE
必须是电脑版的CK吗？

### ISSUE THREAD

**Issue by penhuowa** [Dimlitter/jd_AutoComment#21]
m.jd.com的CK可以吗？本来想在青龙面板运行可是一直安装不上lxml这个依赖，没办法，在服务器新能跑成功

**Comment by Dimlitter** [comment]
不行，因为电脑版和手机版网页布局不一样，可以找原作者的库，他写了手机版的评价。
## 关于lxml的解决方法:
1.手动安装，下载wheel文件安装
2.如果有能力的话可以直接把xpath换成正则表达式，直接用re模块

**Comment by penhuowa** [comment]
感谢大佬

**Comment by Cyiming** [comment]
青龙运行意义不大 ck时效短

**Comment by rootphantomer** [comment]
> m.jd.com的CK可以吗？本来想在青龙面板运行可是一直安装不上lxml这个依赖，没办法，在服务器新能跑成功

可以使用，记得复制完全 ck。我用的就是https://bean.m.jd.com/下的。
