### ISSUE TITLE
服务评价不能评价吗

### ISSUE THREAD

**Issue by xiaochenbing** [Dimlitter/jd_AutoComment#26]
![屏幕截图 2022-07-30 222431](https://user-images.githubusercontent.com/86729835/181918815-1468d1ae-1808-4e64-8cb5-396d8fa19810.jpg)

**Comment by Dimlitter** [comment]
测试时没有发现此问题。

可以切换稳定版分支再行尝试

**Comment by xiaochenbing** [comment]
![image](https://user-images.githubusercontent.com/86729835/182352529-f0175fc5-9ab5-4322-b01e-6e8c2269acf5.png)
换成稳定版就出现这了

**Comment by Dimlitter** [comment]
![image](https://user-images.githubusercontent.com/68945228/182506430-cb9a3af4-fc80-4ca8-95df-1dea01b1b0da.png)

我本地尝试未出现以上情况，因账号特异性，无法复现此问题，也无法解决。

您可以尝试更改稳定版报错位置的xpath路径（line266）再行尝试，期待您的PR！
