### ISSUE TITLE
爬取不到信息是哪里没配置好吗？

### ISSUE THREAD

**Issue by applusuck** [Dimlitter/jd_AutoComment#27]
![image](https://user-images.githubusercontent.com/86282095/190858157-05b26731-ebcb-4ba8-84e3-7fdccf79d499.png)
爬取不到信息是哪里没配置好吗？

**Comment by Dimlitter** [comment]
可能是当前商品比较冷门，还没有评论=-=

您看看别的商品有出现这样的情况么？

**Comment by applusuck** [comment]
> 可能是当前商品比较冷门，还没有评论=-=
> 
> 您看看别的商品有出现这样的情况么？

所有的商品都是这样，区别就是有的商品爬取的次数多，有的爬取的次数少

**Comment by Dimlitter** [comment]
> > 可能是当前商品比较冷门，还没有评论=-=
> > 
> > 您看看别的商品有出现这样的情况么？
> 
> 所有的商品都是这样，区别就是有的商品爬取的次数多，有的爬取的次数少

等我有空我会看看的==

**Comment by ySirius** [comment]
> > > 可能是当前商品比较冷门，还没有评论=-=
> > > 您看看别的商品有出现这样的情况么？
> > 
> > 
> > 所有的商品都是这样，区别就是有的商品爬取的次数多，有的爬取的次数少
> 
> 等我有空我会看看的==

在jdspider.py的getHeaders中添加 cookie就好了，现在应该是爬取内容也需要登录了

**Comment by Dimlitter** [comment]
> > > > 可能是当前商品比较冷门，还没有评论=-=
> > > > 您看看别的商品有出现这样的情况么？
> > > 
> > > 
> > > 所有的商品都是这样，区别就是有的商品爬取的次数多，有的爬取的次数少
> > 
> > 等我有空我会看看的==
> 
> 在jdspider.py的getHeaders中添加 cookie就好了，现在应该是爬取内容也需要登录了

感谢反馈！不知道您有时间提个PR吗

**Comment by ySirius** [comment]
> > > > > 可能是当前商品比较冷门，还没有评论=-=
> > > > > 您看看别的商品有出现这样的情况么？
> > > > 
> > > > 
> > > > 所有的商品都是这样，区别就是有的商品爬取的次数多，有的爬取的次数少
> > > 
> > > 
> > > 等我有空我会看看的==
> > 
> > 
> > 在jdspider.py的getHeaders中添加 cookie就好了，现在应该是爬取内容也需要登录了
> 
> 感谢反馈！不知道您有时间提个PR吗

好的 马上提
