### ISSUE TITLE
无法带图评价

### ISSUE THREAD

**Issue by lhr19971010** [Dimlitter/jd_AutoComment#30]
评价的时候带不了图片，不知道是本身就不支持带图评价还是哪里有问题呢

**Comment by Dimlitter** [comment]
已了解，后续将修复这一问题

**Comment by xxp2277** [comment]
> 

大佬，先将“待晒单”这个菜单取消吧，好歹能正常运行完所有评论。

**Comment by Dimlitter** [comment]
已在https://github.com/Dimlitter/jd_AutoComment/commit/e6c4c29d9f395303a53449e7ce0fac590c7a9f17 中修复，原因是[京东页面](https://club.jd.com/myJdcomments/myJdcomment.action)删除了“晒单评价”一栏，改为“已评价”。
