### ISSUE TITLE
提示ck错误的bug

### ISSUE THREAD

**Issue by ssmmtt** [Dimlitter/jd_AutoComment#35]
![image](https://user-images.githubusercontent.com/16244320/203899609-d04eea73-762d-4838-9188-0fbff7bdd385.png)
这个地方有个 > 200的判断条件，导致一直报ck不对的错，我这实际cookie长度是小于200的。

**Comment by Dimlitter** [comment]
请说明需要更改的文件以及行数，以及...我好像没写过多账户运行?

**Comment by ssmmtt** [comment]
提交错仓库了。。。
