### ISSUE TITLE
写的比我好多了，不过好像爬取评论有bug

### ISSUE THREAD

**Issue by Ocyss** [Dimlitter/jd_AutoComment#36]
![1](https://user-images.githubusercontent.com/68412205/204703344-cddff765-ee36-4864-93c9-59d7e850701d.png)
虽然报错看着挺多的，但最后总能评论完。
看输出应该是爬取别人的评论
1.如果评论量很大，会不会被京东检测到，黑号啥的
2.源码没注释也看不懂，不知道是多条组合还是就一模一样，如果一模一样会不会被判断无效评论

之前写的时候，一方面电脑版自己用，另一方面安卓版造福大家，还有安卓最终版那时候也没写完就没上传了。
我之前一直想按手机上的那个评价官来写，可以唤起小标签，然后根据商品名和标签名，让ai来写评论。不过一直没啥时间。

我看最近他们青龙都好像有挂评论脚本，也不知道是谁写的

**Comment by Dimlitter** [comment]
哈哈哈，大佬谬赞了。这个脚本只是我刚学python的时候突发奇想拼凑出来的，基本还是依赖您的xpath等等写好的框架。
另外这些error是另一位开发者加的日志系统，好像不是很完善，有许多的重复= =

回答您的几个问题:
1、评论量大基本不会导致黑号，但是评论时间间隔过小很可能导致请求接口返回错误，将会导致短暂时间的所谓“黑号”，大约在两小时左右就会恢复
2、爬取的评价经过分词之后会出现很多空格和单独存在的标准符号，所以加了个判断去除，最终的呈现是多个评论直接相加

还有青龙那个脚本...是位开发者直接搬了我的脚本加了青龙适配和多账号的循环...没什么技术含量的更新= =也在这里提示下请遵守MIT开源协议～

我最近也很忙...好久没碰技术这块了，也很久没来维护这个项目，希望有更多的喜欢python实际应用的大佬们一起加入^ ^
