### ISSUE TITLE
你好，为什么我在pc跑了以后，评价都是乱码

### ISSUE THREAD

**Issue by davget** [Dimlitter/jd_AutoComment#39]
![E99R3PK}56~6B`CW0)8$SVM](https://user-images.githubusercontent.com/83133164/236178323-b148b6e4-922c-4bbf-91e4-73afec4f517d.png)

**Comment by davget** [comment]
爬取的评价没问题，但是完成以后是乱码
![JZ)6F_@HVK8~FPM_MT{8QQF](https://user-images.githubusercontent.com/83133164/236179330-10c34cbb-535c-49d7-a337-8cb9a65803b8.png)

**Comment by davget** [comment]
同一次用脚本评价的商品，大约三分之二商品评价都是乱码，其他的商品评价都正常

**Comment by Chikit-L** [comment]
一样

**Comment by lzy9666** [comment]
一样的乱码，不修改完善一下吗？

**Comment by 6x111111** [comment]
一样是乱码

**Comment by rootphantomer** [comment]
我改了一下，https://github.com/rootphantomer/jd_AutoComment/tree/Fix_garbled_code，我目前没有待评价的订单了，试试看能不能用

**Comment by rootphantomer** [comment]
> 我改了一下，https://github.com/rootphantomer/jd_AutoComment/tree/Fix_garbled_code ，Fix_garbled_code分支的代码，我目前没有待评价的订单了，试试看能不能用，能用我就pr上去给作者

这个pr已经被合并到main分支，有空大家可以帮看看还有问题吗。（因手头上没有大量未评价订单）

**Comment by Inliang** [comment]
> > 我改图，[https://github.com/rootphantomer/jd_AutoComment/tree/Fix_garbled_code，Fix_garbled_code](https://github.com/rootphantomer/jd_AutoComment/tree/Fix_garbled_code)分支的代码，我目前还没有评价待定的订单了，试试看能不能用，能用我就pr上去给作者
> 
> 这个已经被合并到主分支了，有空的大家可以使用最新的主分支运行看看还有问题吗。（因手头没有大量未评价订单）

库被和谐了

**Comment by rootphantomer** [comment]
> > > 我改图，[https://github.com/rootphantomer/jd_AutoComment/tree/Fix_garbled_code，Fix_garbled_code](https://github.com/rootphantomer/jd_AutoComment/tree/Fix_garbled_code)分支的代码，我目前还没有评价待定的订单了，试试看能不能用，能用我就pr上去给作者
> > 
> > 
> > 这个已经被合并到主分支了，有空的大家可以使用最新的主分支运行看看还有问题吗。（因手头没有大量未评价订单）
> 
> 库被和谐了

你直接用主分支，已经更新上去了
