### ISSUE TITLE
评价过程中报错

### ISSUE THREAD

**Issue by LAGOD777** [Dimlitter/jd_AutoComment#42]
<img width="954" alt="image" src="https://github.com/Dimlitter/jd_AutoComment/assets/6783240/7f2ad3a5-8dc0-4cf2-bb03-bdf6bb235bc6">

**Comment by rootphantomer** [comment]
图片获取失败了。正常情况下应该是：
![image](https://github.com/Dimlitter/jd_AutoComment/assets/6481352/77143ca6-836d-4f69-8d72-574d25831221)
