### ISSUE TITLE
请问评价中图片的数量能否修改呢

### ISSUE THREAD

**Issue by Chikit-L** [Dimlitter/jd_AutoComment#44]
请问能不能通过修改配置来添加评价中图片的数量？
京东评价官任务需要 `每次60字+2图/视频`，现在通过脚本60字部分可以达到，但是图片只有一张图片。
所以想问一下有没有地方可以修改一下配置来抓取两张图片进行评价，这样在完成评价的同时可以完成评价官的任务。
谢谢大佬

**Comment by rootphantomer** [comment]
> 请问能不能通过修改配置来添加评价中图片的数量？ 京东评价官任务需要 `每次60字+2图/视频`，现在通过脚本60字部分可以达到，但是图片只有一张图片。 所以想问一下有没有地方可以修改一下配置来抓取两张图片进行评价，这样在完成评价的同时可以完成评价官的任务。 谢谢大佬

```
{
                'orderId': oid,
                'productId': pid,  # 商品id
                'score': str(xing),  # 商品几星
                'content': Str,  # 评价内容
                'saveStatus': '1',
                'anonymousFlag': '1',  # 是否匿名
                'imgs': imgurl,  # 图片url
            }
```
抓包看看imgs两张图片上传的时候的请求包是什么样子，我暂时没有未评价的商品。

**Comment by Chikit-L** [comment]
body={"addPictureFlag":"0","anonymousFlag":"1","category":"652;829;854","categoryList":"[652+数码,+829+数码配件,+854+电池/充电器]","commentData":"京东yyds","commentScore":"5","commentType":null,"evaAuraVersion":"120202","extInfo":{"mediasExt":"[{\"ImageTakePhotoFilterId\":\"0\",\"VideoIsEditCrop\":\"0\",\"VideoRecordIsMakup\":\"0\",\"ImageIsCrop\":\"0\",\"ImageEditFilterId\":\"0\",\"TakeRate\":\"0\",\"VideoPropId\":\"0\",\"FromType\":\"1\",\"ImagePropId\":\"0\",\"ImageTakePhotoIsMakup\":\"0\",\"ImageStrickId\":\"0\",\"VideoIsEditCover\":\"0\",\"VideoEditFilterId\":\"0\",\"VideoRecordFilterId\":\"0\",\"VideoMusicId\":\"0\",\"ImageFontId\":\"0\"},{\"ImageTakePhotoFilterId\":\"0\",\"VideoIsEditCrop\":\"0\",\"VideoRecordIsMakup\":\"0\",\"ImageIsCrop\":\"0\",\"ImageEditFilterId\":\"0\",\"TakeRate\":\"0\",\"VideoPropId\":\"0\",\"FromType\":\"1\",\"ImagePropId\":\"0\",\"ImageTakePhotoIsMakup\":\"0\",\"ImageStrickId\":\"0\",\"VideoIsEditCover\":\"0\",\"VideoEditFilterId\":\"0\",\"VideoRecordFilterId\":\"0\",\"VideoMusicId\":\"0\",\"ImageFontId\":\"0\"}]","showShop":"0"},"isCommentTagContent":"0","jshowActivityId":"","officerLevel":"1","officerScore":"303","orderId":"281144521639","pictureInfoList":[{"picUrl":"https://img30.360buyimg.com/shaidan/jfs/t1/236996/33/4478/122731/6561e115Fba2590bd/030602129f5200e7.jpg"},{"picUrl":"https://img30.360buyimg.com/shaidan/jfs/t1/233047/1/4421/98201/6561e116F92d64d40/4552eec9d3fde82d.jpg"}],"productId":"3414091","shopId":"1000000492","shopType":"0","syncStoryFlag":"","verticalTagList":null,"videoInfoList":[],"voucherStatus":"0"}
 
 
 我抓的好像不太一样？

**Comment by rootphantomer** [comment]
@Chikit-L 试试，pr上去了。

**Comment by Chikit-L** [comment]
> @Chikit-L 试试，pr上去了。

谢谢大佬 我试一下
