### ISSUE TITLE
cfg的user和cookie 的填法和填的内容能给个示例不？

### ISSUE THREAD

**Issue by lious68** [Dimlitter/jd_AutoComment#5]

**Comment by Dimlitter** [comment]
最简单的ck是 ck = 'thor=; pin=;'
实际上抓到电脑版ck直接丢进去就行

**Comment by zrtalent** [comment]
File "auto_comment_plus.py", line 98
    url = (f'https://club.jd.com/myJdcomments/myJdcomment.action?sort=0&'
                                                                        ^
SyntaxError: invalid syntax

执行后提示这个错误是不是标点哪里有问题？

**Comment by Dimlitter** [comment]
> File "auto_comment_plus.py", line 98 url = (f'https://club.jd.com/myJdcomments/myJdcomment.action?sort=0&' ^ SyntaxError: invalid syntax
> 
> 执行后提示这个错误是不是标点哪里有问题？

我这测试没有问题，请复现一下使用场景和环境

**Comment by zrtalent** [comment]
我在执行python auto_comment_plus.py 时候这样提示的：
MacBook-Pro jd_AutoComment % python auto_comment_plus.py
  File "auto_comment_plus.py", line 98
    url = (f'https://club.jd.com/myJdcomments/myJdcomment.action?sort=0&'
                                                                        ^
SyntaxError: invalid syntax

**Comment by lious68** [comment]
真没看到CK这个字段。
![image](https://user-images.githubusercontent.com/15836048/153867471-9f6d4d00-1203-44f8-be5f-f9a3b4ca576f.png)

**Comment by zrtalent** [comment]
> 真没看到CK这个字段。 ![image](https://user-images.githubusercontent.com/15836048/153867471-9f6d4d00-1203-44f8-be5f-f9a3b4ca576f.png)
找thor=; pin=; 这两个字断即可

**Comment by lious68** [comment]
然后怎么填呢？

**Comment by Dimlitter** [comment]
> 然后怎么填呢？

都在ck里，全丢进去就行
你自己改 headers 也可

**Comment by lious68** [comment]
不知道我的理解对不对，这里的ck就是整个cookie。
![image](https://user-images.githubusercontent.com/15836048/153909474-123d5296-aa5b-4c4f-9661-3cd4308ebfc3.png)
即：
![image](https://user-images.githubusercontent.com/15836048/153909714-952a660a-df41-43dc-bea7-1314893455cd.png)

但是我在运行的时候说ck是错误的。

**Comment by Dimlitter** [comment]
> > > File "auto_comment_plus.py", line 98 url = (f'https://club.jd.com/myJdcomments/myJdcomment.action?sort=0&' ^ SyntaxError: invalid syntax
> > > 执行后提示这个错误是不是标点哪里有问题？
> > 
> > 
> > 我这测试没有问题，请复现一下使用场景和环境
> 
> 前几步执行pip requirements.txt都安装成功 <img alt="Snipaste_2022-02-14_20-44-46" width="557" src="https://user-images.githubusercontent.com/7744503/153866591-500a475a-9b41-4004-9787-9c5bea976127.png"> 了

破案了，python版本过低，升级下python3

**Comment by Ike-li** [comment]
> 
python3 auto_comment_plus.py
macOS 或者 Linux 默认 python2.xxx

**Comment by zrtalent** [comment]
> > > > File "auto_comment_plus.py", line 98 url = (f'https://club.jd.com/myJdcomments/myJdcomment.action?sort=0&' ^ SyntaxError: invalid syntax
> > > > 执行后提示这个错误是不是标点哪里有问题？
> > > 
> > > 
> > > 我这测试没有问题，请复现一下使用场景和环境
> > 
> > 
> > 前几步执行pip requirements.txt都安装成功 <img alt="Snipaste_2022-02-14_20-44-46" width="557" src="https://user-images.githubusercontent.com/7744503/153866591-500a475a-9b41-4004-9787-9c5bea976127.png"> 了
> 
> 破案了，python版本过低，升级下python3

对，我升级py3就好了，已经评价上了，非常给力，赚了4000豆了

**Comment by Ike-li** [comment]
> > > > > File "auto_comment_plus.py", line 98 url = (f'https://club.jd.com/myJdcomments/myJdcomment.action?sort=0&' ^ SyntaxError: invalid syntax
> > > > > 执行后提示这个错误是不是标点哪里有问题？
> > > > 
> > > > 
> > > > 我这测试没有问题，请复现一下使用场景和环境
> > > 
> > > 
> > > 前几步执行pip requirements.txt都安装成功 <img alt="Snipaste_2022-02-14_20-44-46" width="557" src="https://user-images.githubusercontent.com/7744503/153866591-500a475a-9b41-4004-9787-9c5bea976127.png"> 了
> > 
> > 
> > 破案了，python版本过低，升级下python3
> 
> 对，我升级py3就好了，已经评价上了，非常给力，赚了4000豆了

cookie 是 pt_key;pt_pin; 还是一大坨ck

**Comment by zrtalent** [comment]
> > > > > > File "auto_comment_plus.py", line 98 url = (f'https://club.jd.com/myJdcomments/myJdcomment.action?sort=0&' ^ SyntaxError: invalid syntax
> > > > > > 执行后提示这个错误是不是标点哪里有问题？
> > > > > 
> > > > > 
> > > > > 我这测试没有问题，请复现一下使用场景和环境
> > > > 
> > > > 
> > > > 前几步执行pip requirements.txt都安装成功 <img alt="Snipaste_2022-02-14_20-44-46" width="557" src="https://user-images.githubusercontent.com/7744503/153866591-500a475a-9b41-4004-9787-9c5bea976127.png"> 了
> > > 
> > > 
> > > 破案了，python版本过低，升级下python3
> > 
> > 
> > 对，我升级py3就好了，已经评价上了，非常给力，赚了4000豆了
> 
> cookie 是 pt_key;pt_pin; 还是一大坨ck

一大坨就行，不用区分

**Comment by LiWeiQiangAndroid** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/17853766/154280102-e30e9c50-6a8a-4e24-83ee-f172c63b9c21.png">
啥情况

**Comment by giterfor126** [comment]
为啥我一直显示
Ck出现错误，请重新抓取！

**Comment by Dimlitter** [comment]
> <img width="900" alt="image" src="https://user-images.githubusercontent.com/17853766/154280102-e30e9c50-6a8a-4e24-83ee-f172c63b9c21.png">
> 啥情况

cookie没读取到，可以把cookie直接填autocommentplus.py里面，把那段用yaml读ck的代码删掉

**Comment by Dimlitter** [comment]
> > 为啥我一直显示 Ck出现错误，请重新抓取！
> 
> 我也一样，新抓的ck也提示CK出现错误

www.jd.com 这里抓取

**Comment by LittleYe233** [comment]
> <img alt="image" width="900" src="https://user-images.githubusercontent.com/17853766/154280102-e30e9c50-6a8a-4e24-83ee-f172c63b9c21.png">
> 啥情况

请给出完整traceback信息，你这下面应该还有一段。

**Comment by LMsolo** [comment]
爬取不到评论，
![image](https://user-images.githubusercontent.com/53147530/156894590-794d421f-54b4-473b-ac11-0c6f74702eac.png)

**Comment by Dimlitter** [comment]
> 爬取不到评论，
> ![image](https://user-images.githubusercontent.com/53147530/156894590-794d421f-54b4-473b-ac11-0c6f74702eac.png)
> 

请查看原商品中是否有评论，这种情况一般会使用默认评论

**Comment by lious68** [comment]
> 找到了个好办法。复制JD的cookie后，用正则直接改
(.*?):(.*)
$1 : "$2"

**Comment by donqee** [comment]
www.jd.com 抓取这里的cookie 就可以啊，移动网的界面肯定会报错的
