### ISSUE TITLE
自动评价乱码怎么解决？

### ISSUE THREAD

**Issue by xiaolousir** [Dimlitter/jd_AutoComment#51]
![2024-1-15 19-40-32](https://github.com/Dimlitter/jd_AutoComment/assets/156669445/49cff959-58c2-4807-a228-310a872a26f3)
好像有人帮忙解决了 我是新手不知道怎么更新到最新版

**Comment by xiaolousir** [comment]
@rootphantomer 怎么更新到你解决的版本啊

**Comment by rootphantomer** [comment]
下载最新的源码就行了

**Comment by xiaolousir** [comment]
> 下载最新的源码就行了

怎么下

**Comment by rootphantomer** [comment]
> > 下载最新的源码就行了
> 
> 是下载code然后解压使用吗 可不可以覆盖以前的

可以覆盖，怎么使用需要你有 python 的环境，如果不知道什么是 python，建议先去百度学一下基础的python 知识。

**Comment by xiaolousir** [comment]
> > > 下载最新的源码就行了
> > 
> > 
> > 是下载code然后解压使用吗 可不可以覆盖以前的
> 
> 可以覆盖，怎么使用需要你有 python 的环境，如果不知道什么是 python，建议先去百度学一下基础的python 知识。

搞定了 谢谢
