### ISSUE TITLE
ck格式

### ISSUE THREAD

**Issue by zdyy2001** [Dimlitter/jd_AutoComment#54]
请问问大佬 ck的格式是什么样的，我尝试了几次一直报错

**Comment by rootphantomer** [comment]
pc  端整个 cookie 字符串

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zdyy2001 ***@***.***>
发送时间: Sunday, July 7, 2024 11:37:50 AM
收件人: Dimlitter/jd_AutoComment ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Dimlitter/jd_AutoComment] ck格式 (Issue #54)


请问问大佬 ck的格式是什么样的，我尝试了几次一直报错

―

**Comment by zdyy2001** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
