### ISSUE TITLE
这是什么问题导致的闪退

### ISSUE THREAD

**Issue by xiaolousir** [Dimlitter/jd_AutoComment#56]
![Uploading 123.jpg…]()

**Comment by rootphantomer** [comment]
看不到图。。

**Comment by xiaolousir** [comment]
![123](https://github.com/user-attachments/assets/52dfaff6-c926-425d-9e30-dfc25f534c90)
@rootphantomer
不好意思 github抽风没上传成功

**Comment by rootphantomer** [comment]
> ![123](https://private-user-images.githubusercontent.com/156669445/349923040-52dfaff6-c926-425d-9e30-dfc25f534c90.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTAxNzksIm5iZiI6MTcyMTMwOTg3OSwicGF0aCI6Ii8xNTY2Njk0NDUvMzQ5OTIzMDQwLTUyZGZhZmY2LWM5MjYtNDI1ZC05ZTMwLWRmYzI1ZjUzNGM5MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMzM3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWViNTJhYTc1YWU1YTJkYjExY2NkYjNkYmJkOGMyODE5ZDYxYzMyMjg1NDNhODQzYmJkNTI1ZWU1OWI3NDYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4jIiBo9sn5QLgqyq0QtXp9IbUz6DsfwisEdl4uN0InI) @rootphantomer 不好意思 github抽风没上传成功 我用的是最新版 CK抓的电脑端的 user: cookie: "''" 双引号也需要保留吗

目测py2版本把。或者py3版本太低了。

**Comment by xiaolousir** [comment]
> > ![123](https://private-user-images.githubusercontent.com/156669445/349923040-52dfaff6-c926-425d-9e30-dfc25f534c90.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTAxNzksIm5iZiI6MTcyMTMwOTg3OSwicGF0aCI6Ii8xNTY2Njk0NDUvMzQ5OTIzMDQwLTUyZGZhZmY2LWM5MjYtNDI1ZC05ZTMwLWRmYzI1ZjUzNGM5MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMzM3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWViNTJhYTc1YWU1YTJkYjExY2NkYjNkYmJkOGMyODE5ZDYxYzMyMjg1NDNhODQzYmJkNTI1ZWU1OWI3NDYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4jIiBo9sn5QLgqyq0QtXp9IbUz6DsfwisEdl4uN0InI) @rootphantomer 不好意思 github抽风没上传成功 我用的是最新版 CK抓的电脑端的 user: cookie: "''" 双引号也需要保留吗
> 
> 目测py2版本把。或者py3版本太低了。把pc的cookie全部填到最中间的两个单引号中间保持即可。

![123](https://github.com/user-attachments/assets/3624fd82-bf90-4e7c-bd55-36378da1a283)
没更新1.2的时候是可以的 WIN7估计用不了更高python了

**Comment by xiaolousir** [comment]
> @xiaolousir 更新下main的最新代码，应该修复了这个问题。

好的 大佬
