### ISSUE TITLE
商品有评价却使用的是默认评价

### ISSUE THREAD

**Issue by xiaolousir** [Dimlitter/jd_AutoComment#58]
以前订单多的时候没在意直接后台 最近的订单都是默认评价

**Comment by xiaolousir** [comment]
![1234](https://github.com/user-attachments/assets/81e5418d-3a69-49e3-9b52-a17a74b71246)

**Comment by rootphantomer** [comment]
> ![1234](https://private-user-images.githubusercontent.com/156669445/351656439-81e5418d-3a69-49e3-9b52-a17a74b71246.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTM1NTAsIm5iZiI6MTcyMTgxMzI1MCwicGF0aCI6Ii8xNTY2Njk0NDUvMzUxNjU2NDM5LTgxZTU0MThkLTNhNjktNDllMy05YjUyLWExN2E3NGI3MTI0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwOTI3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTgwNDdjNzg5YTE5YzI3NzAzYzQ0NTEwNWFkNGJkNzI1MDc3ZjJlMDQwNjcyMjM0NDJhN2FiZTJkOTRlZWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fSbo2fqwVJOE8OfOARQYpY5BqLIeGinC8114gOczFsA)

每一个商品都是默认评价？？？我看日志里是这个商品没有评价结果才用默认评价的。

**Comment by rootphantomer** [comment]
![image](https://github.com/user-attachments/assets/87514881-ee29-4c09-a5eb-d3afd77dc620)
我刚测试的，没问题，如果是个别订单的问题，只能等我出现类似的订单了我再研究一下是什么问题。

**Comment by rootphantomer** [comment]
@xiaolousir 把 main 分支的代码更新到最新，如果后续还遇到了这样子的问题，就把日志以文本形式全部贴出来。到时候我从日志里看看到底是什么情况。

**Comment by xiaolousir** [comment]
> @xiaolousir 把 main 分支的代码更新到最新，我改了一些日志输出的代码，如果后续还遇到了这样子的问题，就把日志以文本形式全部贴出来。到时候我从日志里看看到底是什么情况。
只剩一个订单试了下应该恢复正常了
![121](https://github.com/user-attachments/assets/625ba857-8a75-4531-ad6c-bad71b2cd6f3)
![122](https://github.com/user-attachments/assets/39ea6690-dc9e-415c-82aa-32be504f2a6e)

**Comment by rootphantomer** [comment]
等有问题的时候再开个issue反馈把。到时候贴里面的log内容成文本出来，不要只是截图。

**Comment by xiaolousir** [comment]
> > ![1234](https://private-user-images.githubusercontent.com/156669445/351656439-81e5418d-3a69-49e3-9b52-a17a74b71246.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTM1NTAsIm5iZiI6MTcyMTgxMzI1MCwicGF0aCI6Ii8xNTY2Njk0NDUvMzUxNjU2NDM5LTgxZTU0MThkLTNhNjktNDllMy05YjUyLWExN2E3NGI3MTI0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwOTI3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTgwNDdjNzg5YTE5YzI3NzAzYzQ0NTEwNWFkNGJkNzI1MDc3ZjJlMDQwNjcyMjM0NDJhN2FiZTJkOTRlZWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fSbo2fqwVJOE8OfOARQYpY5BqLIeGinC8114gOczFsA)
> 
> 每一个商品都是默认评价？？？我看日志里是这个商品没有评价结果才用默认评价的。
> 
> 你把最近的几个商品评价的内容贴图一下，我看看评价内容。

![111](https://github.com/user-attachments/assets/d5bb345a-e362-451f-b1b3-368771ae4683)
![222](https://github.com/user-attachments/assets/37e8c907-1b4b-448b-b201-9ca55b70f684)
用电脑端截了俩

**Comment by xiaolousir** [comment]
> 等有问题的订单时候再开个issue反馈把。到时候贴里面的log内容成文本出来，不要只是截图。

好的
