### ISSUE TITLE
多账号的需求看这里解决

### ISSUE THREAD

**Issue by jjjyyyllll** [Dimlitter/jd_AutoComment#6]
大佬 支持多账号吗？ 如果多账号的话怎么配置CK？换行 @还是什么的？

**Comment by Dimlitter** [comment]
目前还不支持

**Comment by skyyaman** [comment]
建议写个多账号的。。。。大神

**Comment by Dimlitter** [comment]
意义不是很大，据我观察网页版cookie有效期只有30min，如果采用循环多账号，可能ck过期了还没评价完。接下来会尝试多线程并发

**Comment by rootphantomer** [comment]
https://github.com/Dimlitter/jd_AutoComment/tree/more_cookie   有空可以试下这个多账号的代码。
