### ISSUE TITLE
能否通过下载图片再上传的方式进行带图评价，目前图片都审核不通过。

### ISSUE THREAD

**Issue by tufeikafei** [Dimlitter/jd_AutoComment#60]
**您的功能请求是否与问题有关？请描述**
目前带图评论 基本都是审核不通过，因为我们用的是别人的链接。

**描述您想要的解决方案**
我的想法是，首先和原来一样，用别人的图片链接下载下来图片。
然后通过 https://club.jd.com/myJdcomments/ajaxUploadImage.action
这个接口 上传你的评价图片，这样这个图片是属于你的。对应的图片新产生的链接都是你的信息。
因为之前的盗用图片链接的接口里面是包含图片的所有者等各种信息

**Comment by rootphantomer** [comment]
> **您的功能请求是否与问题有关？请描述** 目前带图评论 基本都是审核不通过，因为我们用的是别人的链接。
> 
> **描述您想要的解决方案** 我的想法是，首先和原来一样，用别人的图片链接下载下来图片。 然后通过 https://club.jd.com/myJdcomments/ajaxUploadImage.action 这个接口 上传你的评价图片，这样这个图片是属于你的。对应的图片新产生的链接都是你的信息。 因为之前的盗用图片链接的接口里面是包含图片的所有者等各种信息

这是已经验证过后的得出的结论，还是猜测的可能性原因？

**Comment by xiaolousir** [comment]
> **您的功能请求是否与问题有关？请描述** 目前带图评论 基本都是审核不通过，因为我们用的是别人的链接。
> 
> **描述您想要的解决方案** 我的想法是，首先和原来一样，用别人的图片链接下载下来图片。 然后通过 https://club.jd.com/myJdcomments/ajaxUploadImage.action 这个接口 上传你的评价图片，这样这个图片是属于你的。对应的图片新产生的链接都是你的信息。 因为之前的盗用图片链接的接口里面是包含图片的所有者等各种信息

我猜测也是这样的 近期抓取的图片都审核不过

**Comment by rootphantomer** [comment]
有能力的话，验证下是不是这个原因导致的问题。验证后给个明确的答复，我着手准备更新代码。不然需要我下次有待评价的时候才能验证了。

**Comment by tufeikafei** [comment]
我等会再测试一遍，前天我粗略测试过，我把同一张图片下载下来后，然后再通过后台上传，这个时候就不会提示审核不过。

**Comment by tufeikafei** [comment]
刚刚又测试了一遍，ok，图片通过审核，通过随机下来两个图片。
来源图片如：
https://img30.360buyimg.com/shaidan/jfs/t1/167248/20/30912/215618/668fa223F102ae054/82ae029382dca94a.jpg
下载后，通过 
https://club.jd.com/myJdcomments/ajaxUploadImage.action
post 方法上传图片 

------WebKitFormBoundaryuy2r0rBdaZgjNEV7
Content-Disposition: form-data; name="name"

晒单2.jpg
------WebKitFormBoundaryuy2r0rBdaZgjNEV7
Content-Disposition: form-data; name="PHPSESSID"

mvpxxxxxxxxxx0b461
------WebKitFormBoundaryuy2r0rBdaZgjNEV7
Content-Disposition: form-data; name="Filedata"; filename="晒单2.jpg"
Content-Type: image/jpeg


------WebKitFormBoundaryuy2r0rBdaZgjNEV7--

返回结果：
jfs/t1/96010/4/47288/68330/66c88754F1d8703a8/2acf9ab6c785e13e.jpg
后面 两张imgurl 用这个接口返回后 上传：
https://img30.360buyimg.com/shaidan/jfs/t1/96010/4/47288/68330/66c88754F1d8703a8/2acf9ab6c785e13e.jpg


评价接口我看依旧：
https://club.jd.com/myJdcomments/saveProductComment.action
post参数：
orderId: 296064751705
productId: 100062743927
score: 5
content: %E8%BF%99%E4%B8%AA%E4%BA%A7%E5%93%81%E6%80%8E%E4%B9%88%E8%AF%B4%E5%91%A2%EF%BC%8C%E4%BB%8E%E5%A4%96%E8%A7%82%E6%88%96%E8%80%85%E8%B4%A8%E9%87%8F%E9%83%BD%E6%98%AF%E5%BE%88%E5%A5%BD%E7%9A%84%EF%BC%8C%E8%BE%BE%E5%88%B0%E4%BA%86%E6%88%91%E7%9A%84%E9%A2%84%E6%9C%9F%E5%80%BC%EF%BC%8C%E5%80%BC%E5%BE%97%E4%B8%80%E4%B8%AA%E5%A5%BD%E8%AF%84%E3%80%82%E7%89%A9%E6%B5%81%E9%80%9F%E5%BA%A6%E4%B9%9F%E5%BE%88%E6%BB%A1%E6%84%8F%EF%BC%8C%E6%95%B4%E4%B8%AA%E4%BA%A4%E6%98%93%E8%BF%87%E7%A8%8B%E5%BE%88%E9%A1%BA%E5%88%A9%EF%BC%8C%E5%BE%88%E5%BC%80%E5%BF%83%E7%9A%84%E4%B8%80%E6%AC%A1%E8%B4%AD%E7%89%A9%E4%BD%93%E9%AA%8C%E3%80%82%0A%E6%84%9F%E8%B0%A2%E5%BF%AB%E9%80%92%E5%B8%88%E5%82%85%EF%BC%8C%E4%B8%80%E6%97%A9%E5%B0%B1%E9%80%81%E6%9D%A5%E3%80%82%E7%BB%99%E5%8A%9B
imgs: //img30.360buyimg.com/shaidan/jfs/t1/78429/29/26780/74895/66c8873cF37c8c445/71863bc767ba022a.jpg,//img30.360buyimg.com/shaidan/jfs/t1/96010/4/47288/68330/66c88754F1d8703a8/2acf9ab6c785e13e.jpg
saveStatus: 2
anonymousFlag: 1

**Comment by tufeikafei** [comment]
测试通过，没有问题。

**Comment by tufeikafei** [comment]
https://github.com/tufeikafei/auto_comment
我修改后 实现了= =不过我用了另外一个。。

**Comment by rootphantomer** [comment]
> https://github.com/tufeikafei/auto_comment 我修改后 实现了= =不过我用了另外一个。。
@tufeikafei 你看看根据main分支clone下来改一个，然后提交个pull request，我这边测试一下没问题，就合并到main分支里。

**Comment by tufeikafei** [comment]
测试有bug= =

**Comment by rootphantomer** [comment]
> 测试有bug= =

可以把问题抛出来，看看有没有社区有没有解决办法。

**Comment by rootphantomer** [comment]
@tufeikafei @xiaolousir 修复了，更新 main 分支的代码有空测测 bug 吧。有问题再新开 issue 吧。

**Comment by xiaolousir** [comment]
> @tufeikafei @xiaolousir 修复了，更新 main 分支的代码有空测测 bug 吧。有问题再新开 issue 吧。

订单太少无法判断 目前俩订单都能正常抓取评论 一个订单审核通过 一个还在审核（抓到的图片跟商品不相干的 ）
![4264228829](https://github.com/user-attachments/assets/932040f0-254c-4278-9f44-6785df8b8bd6)
-----------------------------------------------------------------------------------------------------------------------
能不能把抓取的图片评价完后自动删除
cookie每次都需要新抓吗

**Comment by rootphantomer** [comment]
1、这次只是代码更新只是把图片下载到本地，再次上传。不涉及图片获取逻辑的修改，也就是说获取不相干的图片是当前商品下面的评论里的所有图片，随机获取了两张下载再上传，假如别人评论的图片三四张里有一两张是不相干的，那你恰好获取到这几张拿去上传评论了就会出现你的评论照片出现不想干的问题，程序能不能判断图片相不相干，目前这块无法实现。

2、能不能把抓取的图片评价完后自动删除
这块代码已经写了，但是没启动，私自认为下载的图片也是log的一部分。下一个版本会把下载的图片都放在一个img的文件夹下，用户自己有空删除，也会给一个运行参数开关，但是默认打开状态，方便后续出问题好排查。

3、cookie每次都需要新抓吗

这个代码逻辑没有变，cookie的失效时间不是有我这边能控制的，要看jd怎么设置。所以失效了就抓，没失效就不抓。没有什么解决方法。

**Comment by xiaolousir** [comment]
> 1、这次代码更新只是把图片下载到本地，再次上传。不涉及图片获取逻辑的修改，也就是说获取不相干的图片是当前商品下面的评论里的所有图片，随机获取了两张下载再上传，假如别人评论的图片三四张里有一两张是不相干的，那你恰好获取到这几张拿去上传评论了就会出现你的评论照片出现不相干的问题，程序不能判断图片相不相干。
> 
> 2、能不能把抓取的图片评价完后自动删除 这块代码已经写了，但是没启动，私自认为下载的图片也是log的一部分。下一个版本会把下载的图片都放在一个img的文件夹下，用户自己有空删除，也会给一个运行参数开关，但是默认打开状态，方便后续出问题好排查。
> 
> 3、cookie每次都需要新抓吗
> 
> 这个代码逻辑没有变，cookie的失效时间不是有我这边能控制的，要看京东怎么设置。所以失效了就抓，没失效就不抓。没有什么解决方法。

了解
