### ISSUE TITLE
依赖包报错

### ISSUE THREAD

**Issue by circle-ss** [Dimlitter/jd_AutoComment#7]
安装依赖时报错，怎么解决？
![image](https://user-images.githubusercontent.com/99711951/154003175-bfb9511c-d9fe-4404-abf4-c44addc07889.png)

**Comment by Dimlitter** [comment]
手动下载lxml库，用wheel安装，善用搜索引擎

**Comment by circle-ss** [comment]
让我来说个人话吧，研究了很久，其实很简单，终端下更新一下pip，然后就可以安装成功了

**Comment by happyskey** [comment]
N1,arm架构的cpu，这个依赖安装不了， 有什么解决方法不

**Comment by Dimlitter** [comment]
> N1,arm架构的cpu，这个依赖安装不了， 有什么解决方法不

目前还没有，几乎整个项目都建立在lxml库的基础上了

**Comment by rootphantomer** [comment]
> N1,arm架构的cpu，这个依赖安装不了， 有什么解决方法不

有 arm 的 lxml 库。
<img width="593" alt="image" src="https://github.com/Dimlitter/jd_AutoComment/assets/6481352/68491367-9a23-4c20-984c-f4a5b6a5e932">
