### ISSUE TITLE
读取评论出错

### ISSUE THREAD

**Issue by HongjieCN** [Dimlitter/jd_AutoComment#8]
![image](https://user-images.githubusercontent.com/57511284/154187117-8bbc281d-3d03-4277-95eb-5f47592a6934.png)

**Comment by Dimlitter** [comment]
应该是网络错误，自己打个断点看下res_json里面有啥，换个ip再试。后续会尝试修复

**Comment by HongjieCN** [comment]
又跑一次好了，真神奇，跑了五小时也没出错，感谢作者
