### ISSUE TITLE
解决完依赖，升级完python3，但是运行1条评价后开始报证书错

### ISSUE THREAD

**Issue by SnakeK** [Dimlitter/jd_AutoComment#9]
环境centos7，python3.7，运行2条评价后报证书错
![8c660c6ebac5ba564b43bdc0cee5a5c](https://user-images.githubusercontent.com/93106021/154196309-88a16881-ac9a-415d-98b2-b20d8eddf1fc.png)

**Comment by Dimlitter** [comment]
``` requests.get()```  加参数 ```verify=False```
#### 不影响爬取的话可改可不改
